project:
  type: website
  output-dir: docs

website:
  title: "Austin ML Journal Club"
  navbar:
    right:
      - about.qmd
      - readme.qmd
      - quarto.qmd
      - reading_list.qmd
      - icon: github
        href: https://github.com/AustinMLJournalClub/AustinMLJournalClub.github.io
      - icon: linkedin
        href: https://www.linkedin.com/company/austin-ml-journal-club
  open-graph: true
format:
  html:
    theme: flatly
    css: styles.css
execute:
  freeze: auto


