project:
  type: website
  output-dir: docs

website:
  title: "Austin ML Journal Club"
  navbar:
    right:
      - about.qmd
      - readme.qmd
      - quarto.qmd
      - icon: github
        href: https://github.com/AustinMLJournalClub/AustinMLJournalClub.github.io
  open-graph: true
format:
  html:
    theme: flatly
    css: styles.css
execute:
  freeze: auto


