project:
  type: website
  output-dir: docs

website:
  title: "Austin MLJC"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AustinMLJournalClub/blog
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css
execute:
  freeze: auto


