project:
  type: website
  output-dir: docs

website:
  title: "Austin ML Journal Club"
  navbar:
    logo: logo.jpeg
    left:
      - about.qmd
      - reading_list.qmd
      - archives.qmd
    right:
      - icon: github
        href: https://github.com/AustinMLJournalClub/AustinMLJournalClub.github.io
      - icon: linkedin
        href: https://www.linkedin.com/company/austin-ml-journal-club
  open-graph: true
  favicon: logo.jpeg
  page-footer:
    center: "© 2022-2025 Austin ML Journal Club | [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
format:
  html:
    theme: cosmo
    css: styles.css
    grid:
      body-width: 900px
    toc: true
    toc-depth: 3
execute:
  freeze: auto


