---
title: "Tips"
---

If you are interested in joining the journal club, please send an email to <hongsup.shin@pm.me>. We will send you an invite to our Discord channel. Check out our [LinkedIn group](https://www.linkedin.com/company/austin-ml-journal-club/) as well.

## Logistics
- We meet **every last Thursday of the month** between 6 pm and 8 pm. Meeting announcement is done through our Discord channel. The schedule can change based on the members' availability.
- We usually meet at one of the many branches in Austin Public Library.

## Presentation
- We take turns to present a paper.
- When announcing what to read, we encourage the presenter to write a few sentences on "why this paper" to motivate others.
- **It doesn't have to be a paper.** It can be a blog post, newspaper article, or even a tool documentation page. We can also use the journal club as a brainstorming session if the presenter wants to discuss a specific work problem they want to talk about.
- Every presenter will be introduced in the [About](https://austinmljournalclub.github.io/about.html) page with a short bio. Participants will be mentioned in the posts.
- Presenters don't have to know everything about the paper, but they should have enough understanding to lead the discussion.

### Guidelines for choosing papers
Reading papers takes a great deal of time. To respect everyone's time, please consider the following criteria when choosing papers:

- Papers that are published or peer-reviewed
- Papers about ideas that are discussed frequently in ML community
- Papers with high citation counts
- Papers from renowned research groups
- Papers that are not too niche in terms of their domain
- Papers that are not too long
- Papers that have many interesting discussing points; this means you can choose a bad paper intentionally

Feel free to share any papers of interest in Discord. We will regularly update our [Reading List page](https://austinmljournalclub.github.io/reading_list.html) to track them.

## Communication
- All major correspondence is made in the Discord channel.
- Meetings are announced in the Discord channel and LinkedIn group.
- Presenters should give others **at least 2 weeks to read the paper**.
- Please notify on Discord about whether you can come next time before the meeting.

## Blogging
- Presenters are welcome to write a blog post about the paper they presented. 
- The blog is hosted through GitHub pages from [our repository](https://github.com/AustinMLJournalClub/AustinMLJournalClub.github.io) and we use the [Quarto](https://quarto.org/) platform. 
- You can write about anything in the post as long as it captures some of our discussion during the meeting.
- **Blogging is optional**. If the presenter is too busy to write the post, Hongsup will write a post instead, or he will suggest the presenter to write it together.
